language: java
script:
- mvn test
- mvn install -DskipTests=true
jdk:
- oraclejdk8
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: HzyNVlN40BAq69VaFe9rxJR6gBBDeyYtc0zMdh7HeREiwZNICroUnSLVr3JXVVHgvzLgzxRtLJ1TDZy1TeRwISwkb9Q4HbNLq4kBmPzvrn0CWMadbbFWVg2fG16MqGCD3YF676ZUeFqAkExfkiwS3ppzOTpFslhCHBz9Egydcj0sUQnGiEJ0urYitU2pnO9dS/pPw97AP3BEsM1D/uX5+k/EdW2xs7GZ++CWhZpsdjWXdoeiYvhS5PQbshLioHdS25BaxhlOPFVstjWSm/E0HkyleMPJFhSJ9iVR9SNN8JLcsyNAQ0vaDV6+RFdKuYMFQClJAkQzus/mzGN2g95vD6Gm1SgfGS7ilOWxti+q2ISDfbluUSEkPBHvg+mZxQ9FsTuZDujieLRs5ZRDU2SgqxG4AN2wohRzC5Ip/rS6FOGcUyZCTPEOR+xWBiV3aBkZmzJsz1uY6rfjoLDWduWCAqgwTeaHnM47vCyVRxwLr1Jt19e0UPaiG/F1VpCNakBjvokl708EgyMe3wtNQZ4ovQj2nIIQEcBgr6q1l/TadFdtwnrLz4DPkcIW0Hep9rUmJkGT48ZU1bS5kwFVV47wQ9klMx7GF1pUmf01/ob+54EbFj6c2i+3w6KQb7Ie/WjkQeAGmQgwPhXVhaHpb1ao4+1Vu22MNLVB4UoPDgJ6U8c=
  app: code-reading
  on:
    repo: kooditeam/Code-reading

